# Generated by Django 4.2.3 on 2023-07-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(db_index=True, max_length=255)),
                ('No_of_guests', models.SmallIntegerField()),
                ('BookingDate', models.DateField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(db_index=True, max_length=255)),
                ('BookingDate', models.DateField(db_index=True)),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Inventory', models.SmallIntegerField()),
            ],
        ),
    ]
